In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Churn_Modelling.csv',index_col = 'RowNumber')

In [4]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1.1+ MB

In [6]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [7]:
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
df.shape

(10000, 13)

In [9]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

# Standardizing the Numerical Columns

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
num_cols=['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']
num_subset=scaler.fit_transform(df[num_cols])

C:\Users\hritv\Anaconda3\envs\myenv3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\hritv\Anaconda3\envs\myenv3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [11]:
X=pd.DataFrame(num_subset,columns=num_cols)

# Joining Categorical Columns to X

In [12]:
X['Geography']=list(df['Geography'])

In [13]:
X['Gender']=list(df['Gender'])

In [14]:
X['HasCrCard']=list(df['HasCrCard'])

In [15]:
X['IsActiveMember']=list(df['IsActiveMember'])

In [16]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary,Geography,Gender,HasCrCard,IsActiveMember
0,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.021886,France,Female,1,1
1,-0.440036,0.198164,-1.387538,0.117350,-0.911583,0.216534,Spain,Female,0,1
2,-1.536794,0.293517,1.032908,1.333053,2.527057,0.240687,France,Female,1,0
3,0.501521,0.007457,-1.387538,-1.225848,0.807737,-0.108918,France,Female,0,0
4,2.063884,0.388871,-1.041760,0.785728,-0.911583,-0.365276,Spain,Female,1,1
...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.007457,-0.004426,-1.225848,0.807737,-0.066419,France,Male,1,0
9996,-1.391939,-0.373958,1.724464,-0.306379,-0.911583,0.027988,France,Male,1,1
9997,0.604988,-0.278604,0.687130,-1.225848,-0.911583,-1.008643,France,Female,0,1
9998,1.256835,0.293517,-0.695982,-0.022608,0.807737,-0.125231,Germany,Male,1,0
9999,1.463771,-1.041433,-0.350204,0.859965,-0.911583,-1.076370,France,Female,1,0

# One Hot Encoding the Categorical Columns

In [17]:
## Convert the categorical features to numerical
X=pd.get_dummies(X,columns=['Geography','Gender'])

In [18]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary,HasCrCard,IsActiveMember,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.021886,1,1,1,0,0,1,0
1,-0.440036,0.198164,-1.387538,0.117350,-0.911583,0.216534,0,1,0,0,1,1,0
2,-1.536794,0.293517,1.032908,1.333053,2.527057,0.240687,1,0,1,0,0,1,0
3,0.501521,0.007457,-1.387538,-1.225848,0.807737,-0.108918,0,0,1,0,0,1,0
4,2.063884,0.388871,-1.041760,0.785728,-0.911583,-0.365276,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.007457,-0.004426,-1.225848,0.807737,-0.066419,1,0,1,0,0,0,1
9996,-1.391939,-0.373958,1.724464,-0.306379,-0.911583,0.027988,1,1,1,0,0,0,1
9997,0.604988,-0.278604,0.687130,-1.225848,-0.911583,-1.008643,0,1,1,0,0,1,0
9998,1.256835,0.293517,-0.695982,-0.022608,0.807737,-0.125231,1,0,0,1,0,0,1
9999,1.463771,-1.041433,-0.350204,0.859965,-0.911583,-1.076370,1,0,1,0,0,1,0

In [19]:
Y=df['Exited'].values

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [33]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [34]:
#Initialize ANN
classifier = Sequential()

In [35]:
#Add input layer and hidden layer
classifier.add(Dense(6, activation = 'relu', input_shape = (X_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

In [36]:
#Add second layer
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [37]:
#Add output layer
classifier.add(Dense(1, activation = 'sigmoid'))

In [38]:
classifier.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 6)                 84
_________________________________________________________________
dropout_1 (Dropout)          (None, 6)                 0
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 42
_________________________________________________________________
dropout_2 (Dropout)          (None, 6)                 0
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 7
=================================================================
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________

In [39]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [40]:
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Train on 7200 samples, validate on 800 samples
Epoch 1/200
 - 0s - loss: 0.5520 - accuracy: 0.7924 - val_loss: 0.5024 - val_accuracy: 0.7950
Epoch 2/200
 - 0s - loss: 0.4922 - accuracy: 0.7947 - val_loss: 0.4569 - val_accuracy: 0.7950
Epoch 3/200
 - 0s - loss: 0.4626 - accuracy: 0.7965 - val_loss: 0.4386 - val_accuracy: 0.7950
Epoch 4/200
 - 0s - loss: 0.4485 - accuracy: 0.8007 - val_loss: 0.4271 - val_accuracy: 0.7962
Epoch 5/200
 - 0s - loss: 0.4440 - accuracy: 0.8053 - val_loss: 0.4215 - val_accuracy: 0.7987
Epoch 6/200
 - 0s - loss: 0.4396 - accuracy: 0.8081 - val_loss: 0.4183 - val_accuracy: 0.8062
Epoch 7/200
 - 0s - loss: 0.4401 - accuracy: 0.8074 - val_loss: 0.4155 - val_accuracy: 0.8100
Epoch 8/200
 - 0s - loss: 0.4369 - accuracy: 0.8099 - val_loss: 0.4126 - val_accuracy: 0.8163
Epoch 9/200
 - 0s - loss: 0.4324 - accuracy: 0.8104 - val_loss: 0.4100 - val_accuracy: 0.8225
Epoch 10/200
 - 0s - loss: 0.4302 - accuracy: 0.8110 - val_loss: 0.4085 - val_accuracy: 0.8238
Epoch 11/200
 - 0s - loss: 0.4300 - accuracy: 0.8138 - val_loss: 0.4055 - val_accuracy: 0.8288
Epoch 12/200
 - 0s - loss: 0.4255 - accuracy: 0.8169 - val_loss: 0.4020 - val_accuracy: 0.8288
Epoch 13/200
 - 0s - loss: 0.4251 - accuracy: 0.8186 - val_loss: 0.3995 - val_accuracy: 0.8288
Epoch 14/200
 - 0s - loss: 0.4292 - accuracy: 0.8157 - val_loss: 0.3984 - val_accuracy: 0.8338
Epoch 15/200
 - 0s - loss: 0.4258 - accuracy: 0.8140 - val_loss: 0.3963 - val_accuracy: 0.8350
Epoch 16/200
 - 0s - loss: 0.4219 - accuracy: 0.8169 - val_loss: 0.3941 - val_accuracy: 0.8375
Epoch 17/200
 - 0s - loss: 0.4219 - accuracy: 0.8182 - val_loss: 0.3928 - val_accuracy: 0.8363
Epoch 18/200
 - 0s - loss: 0.4183 - accuracy: 0.8186 - val_loss: 0.3888 - val_accuracy: 0.8363
Epoch 19/200
 - 0s - loss: 0.4182 - accuracy: 0.8200 - val_loss: 0.3859 - val_accuracy: 0.8375
Epoch 20/200
 - 0s - loss: 0.4148 - accuracy: 0.8222 - val_loss: 0.3826 - val_accuracy: 0.8375
Epoch 21/200
 - 0s - loss: 0.4128 - accuracy: 0.8217 - val_loss: 0.3812 - val_accuracy: 0.8413
Epoch 22/200
 - 0s - loss: 0.4143 - accuracy: 0.8221 - val_loss: 0.3780 - val_accuracy: 0.8413
Epoch 23/200
 - 0s - loss: 0.4095 - accuracy: 0.8215 - val_loss: 0.3750 - val_accuracy: 0.8413
Epoch 24/200
 - 0s - loss: 0.4075 - accuracy: 0.8214 - val_loss: 0.3722 - val_accuracy: 0.8413
Epoch 25/200
 - 0s - loss: 0.4064 - accuracy: 0.8264 - val_loss: 0.3711 - val_accuracy: 0.8425
Epoch 26/200
 - 0s - loss: 0.4053 - accuracy: 0.8294 - val_loss: 0.3680 - val_accuracy: 0.8413
Epoch 27/200
 - 0s - loss: 0.4057 - accuracy: 0.8294 - val_loss: 0.3677 - val_accuracy: 0.8425
Epoch 28/200
 - 0s - loss: 0.4007 - accuracy: 0.8294 - val_loss: 0.3635 - val_accuracy: 0.8475
Epoch 29/200
 - 0s - loss: 0.3963 - accuracy: 0.8282 - val_loss: 0.3622 - val_accuracy: 0.8438
Epoch 30/200
 - 0s - loss: 0.3992 - accuracy: 0.8335 - val_loss: 0.3602 - val_accuracy: 0.8438
Epoch 31/200
 - 0s - loss: 0.3992 - accuracy: 0.8344 - val_loss: 0.3611 - val_accuracy: 0.8388
Epoch 32/200
 - 0s - loss: 0.3961 - accuracy: 0.8365 - val_loss: 0.3574 - val_accuracy: 0.8425
Epoch 33/200
 - 0s - loss: 0.3958 - accuracy: 0.8335 - val_loss: 0.3576 - val_accuracy: 0.8425
Epoch 34/200
 - 0s - loss: 0.3932 - accuracy: 0.8346 - val_loss: 0.3543 - val_accuracy: 0.8425
Epoch 35/200
 - 0s - loss: 0.3940 - accuracy: 0.8381 - val_loss: 0.3543 - val_accuracy: 0.8487
Epoch 36/200
 - 0s - loss: 0.3953 - accuracy: 0.8363 - val_loss: 0.3526 - val_accuracy: 0.8462
Epoch 37/200
 - 0s - loss: 0.3927 - accuracy: 0.8381 - val_loss: 0.3512 - val_accuracy: 0.8475
Epoch 38/200
 - 0s - loss: 0.3896 - accuracy: 0.8388 - val_loss: 0.3505 - val_accuracy: 0.8537
Epoch 39/200
 - 0s - loss: 0.3914 - accuracy: 0.8375 - val_loss: 0.3493 - val_accuracy: 0.8600
Epoch 40/200
 - 0s - loss: 0.3890 - accuracy: 0.8393 - val_loss: 0.3498 - val_accuracy: 0.8525
Epoch 41/200
 - 0s - loss: 0.3920 - accuracy: 0.8383 - val_loss: 0.3499 - val_accuracy: 0.8525
Epoch 42/200
 - 0s - loss: 0.3891 - accuracy: 0.8364 - val_loss: 0.3484 - val_accuracy: 0.8562
Epoch 43/200
 - 0s - loss: 0.3872 - accuracy: 0.8392 - val_loss: 0.3454 - val_accuracy: 0.8587
Epoch 44/200
 - 0s - loss: 0.3879 - accuracy: 0.8419 - val_loss: 0.3478 - val_accuracy: 0.8562
Epoch 45/200
 - 0s - loss: 0.3882 - accuracy: 0.8343 - val_loss: 0.3452 - val_accuracy: 0.8587
Epoch 46/200
 - 0s - loss: 0.3853 - accuracy: 0.8415 - val_loss: 0.3447 - val_accuracy: 0.8562
Epoch 47/200
 - 0s - loss: 0.3891 - accuracy: 0.8388 - val_loss: 0.3440 - val_accuracy: 0.8587
Epoch 48/200
 - 0s - loss: 0.3892 - accuracy: 0.8381 - val_loss: 0.3412 - val_accuracy: 0.8587
Epoch 49/200
 - 0s - loss: 0.3879 - accuracy: 0.8393 - val_loss: 0.3409 - val_accuracy: 0.8612
Epoch 50/200
 - 0s - loss: 0.3880 - accuracy: 0.8361 - val_loss: 0.3420 - val_accuracy: 0.8612
Epoch 51/200
 - 0s - loss: 0.3872 - accuracy: 0.8397 - val_loss: 0.3418 - val_accuracy: 0.8562
Epoch 52/200
 - 0s - loss: 0.3885 - accuracy: 0.8381 - val_loss: 0.3402 - val_accuracy: 0.8587
Epoch 53/200
 - 0s - loss: 0.3863 - accuracy: 0.8394 - val_loss: 0.3399 - val_accuracy: 0.8587
Epoch 54/200
 - 0s - loss: 0.3843 - accuracy: 0.8424 - val_loss: 0.3401 - val_accuracy: 0.8562
Epoch 55/200
 - 0s - loss: 0.3847 - accuracy: 0.8431 - val_loss: 0.3395 - val_accuracy: 0.8612
Epoch 56/200
 - 0s - loss: 0.3818 - accuracy: 0.8429 - val_loss: 0.3388 - val_accuracy: 0.8637
Epoch 57/200
 - 0s - loss: 0.3883 - accuracy: 0.8419 - val_loss: 0.3406 - val_accuracy: 0.8612
Epoch 58/200
 - 0s - loss: 0.3863 - accuracy: 0.8414 - val_loss: 0.3411 - val_accuracy: 0.8637
Epoch 59/200
 - 0s - loss: 0.3888 - accuracy: 0.8407 - val_loss: 0.3402 - val_accuracy: 0.8650
Epoch 60/200
 - 0s - loss: 0.3843 - accuracy: 0.8436 - val_loss: 0.3374 - val_accuracy: 0.8625
Epoch 61/200
 - 0s - loss: 0.3866 - accuracy: 0.8396 - val_loss: 0.3390 - val_accuracy: 0.8612
Epoch 62/200
 - 0s - loss: 0.3871 - accuracy: 0.8403 - val_loss: 0.3385 - val_accuracy: 0.8612
Epoch 63/200
 - 0s - loss: 0.3805 - accuracy: 0.8422 - val_loss: 0.3347 - val_accuracy: 0.8650
Epoch 64/200
 - 0s - loss: 0.3861 - accuracy: 0.8429 - val_loss: 0.3367 - val_accuracy: 0.8662
Epoch 65/200
 - 0s - loss: 0.3824 - accuracy: 0.8411 - val_loss: 0.3377 - val_accuracy: 0.8612
Epoch 66/200
 - 0s - loss: 0.3853 - accuracy: 0.8417 - val_loss: 0.3377 - val_accuracy: 0.8625
Epoch 67/200
 - 0s - loss: 0.3836 - accuracy: 0.8433 - val_loss: 0.3367 - val_accuracy: 0.8625
Epoch 68/200
 - 0s - loss: 0.3818 - accuracy: 0.8431 - val_loss: 0.3406 - val_accuracy: 0.8625
Epoch 69/200
 - 0s - loss: 0.3799 - accuracy: 0.8422 - val_loss: 0.3383 - val_accuracy: 0.8625
Epoch 70/200
 - 0s - loss: 0.3801 - accuracy: 0.8417 - val_loss: 0.3356 - val_accuracy: 0.8637
Epoch 71/200
 - 0s - loss: 0.3832 - accuracy: 0.8400 - val_loss: 0.3377 - val_accuracy: 0.8625
Epoch 72/200
 - 0s - loss: 0.3831 - accuracy: 0.8433 - val_loss: 0.3375 - val_accuracy: 0.8650
Epoch 73/200
 - 0s - loss: 0.3835 - accuracy: 0.8425 - val_loss: 0.3359 - val_accuracy: 0.8612
Epoch 74/200
 - 0s - loss: 0.3832 - accuracy: 0.8439 - val_loss: 0.3360 - val_accuracy: 0.8662
Epoch 75/200
 - 0s - loss: 0.3833 - accuracy: 0.8424 - val_loss: 0.3334 - val_accuracy: 0.8650
Epoch 76/200
 - 0s - loss: 0.3889 - accuracy: 0.8363 - val_loss: 0.3345 - val_accuracy: 0.8625
Epoch 77/200
 - 0s - loss: 0.3814 - accuracy: 0.8422 - val_loss: 0.3342 - val_accuracy: 0.8625
Epoch 78/200
 - 0s - loss: 0.3825 - accuracy: 0.8404 - val_loss: 0.3360 - val_accuracy: 0.8600
Epoch 79/200
 - 0s - loss: 0.3832 - accuracy: 0.8468 - val_loss: 0.3382 - val_accuracy: 0.8650
Epoch 80/200
 - 0s - loss: 0.3820 - accuracy: 0.8421 - val_loss: 0.3354 - val_accuracy: 0.8650
Epoch 81/200
 - 0s - loss: 0.3798 - accuracy: 0.8422 - val_loss: 0.3355 - val_accuracy: 0.8625
Epoch 82/200
 - 0s - loss: 0.3836 - accuracy: 0.8438 - val_loss: 0.3354 - val_accuracy: 0.8650
Epoch 83/200
 - 0s - loss: 0.3822 - accuracy: 0.8392 - val_loss: 0.3393 - val_accuracy: 0.8600
Epoch 84/200
 - 0s - loss: 0.3826 - accuracy: 0.8401 - val_loss: 0.3348 - val_accuracy: 0.8637
Epoch 85/200
 - 0s - loss: 0.3828 - accuracy: 0.8411 - val_loss: 0.3372 - val_accuracy: 0.8637
Epoch 86/200
 - 0s - loss: 0.3895 - accuracy: 0.8414 - val_loss: 0.3385 - val_accuracy: 0.8612

Epoch 87/200
 - 0s - loss: 0.3798 - accuracy: 0.8411 - val_loss: 0.3385 - val_accuracy: 0.8612
Epoch 88/200
 - 0s - loss: 0.3858 - accuracy: 0.8407 - val_loss: 0.3425 - val_accuracy: 0.8650
Epoch 89/200
 - 0s - loss: 0.3866 - accuracy: 0.8393 - val_loss: 0.3404 - val_accuracy: 0.8675
Epoch 90/200
 - 0s - loss: 0.3854 - accuracy: 0.8382 - val_loss: 0.3396 - val_accuracy: 0.8612
Epoch 91/200
 - 0s - loss: 0.3801 - accuracy: 0.8393 - val_loss: 0.3401 - val_accuracy: 0.8612
Epoch 92/200
 - 0s - loss: 0.3828 - accuracy: 0.8397 - val_loss: 0.3361 - val_accuracy: 0.8625
Epoch 93/200
 - 0s - loss: 0.3811 - accuracy: 0.8429 - val_loss: 0.3365 - val_accuracy: 0.8650
Epoch 94/200
 - 0s - loss: 0.3799 - accuracy: 0.8439 - val_loss: 0.3371 - val_accuracy: 0.8600
Epoch 95/200
 - 0s - loss: 0.3821 - accuracy: 0.8399 - val_loss: 0.3374 - val_accuracy: 0.8650
Epoch 96/200
 - 0s - loss: 0.3804 - accuracy: 0.8433 - val_loss: 0.3364 - val_accuracy: 0.8662
Epoch 97/200
 - 0s - loss: 0.3780 - accuracy: 0.8417 - val_loss: 0.3359 - val_accuracy: 0.8625
Epoch 98/200
 - 0s - loss: 0.3798 - accuracy: 0.8442 - val_loss: 0.3340 - val_accuracy: 0.8650
Epoch 99/200
 - 0s - loss: 0.3826 - accuracy: 0.8404 - val_loss: 0.3379 - val_accuracy: 0.8650
Epoch 100/200
 - 0s - loss: 0.3802 - accuracy: 0.8396 - val_loss: 0.3378 - val_accuracy: 0.8587
Epoch 101/200
 - 0s - loss: 0.3765 - accuracy: 0.8442 - val_loss: 0.3368 - val_accuracy: 0.8662
Epoch 102/200
 - 0s - loss: 0.3785 - accuracy: 0.8440 - val_loss: 0.3379 - val_accuracy: 0.8637
Epoch 103/200
 - 0s - loss: 0.3778 - accuracy: 0.8439 - val_loss: 0.3343 - val_accuracy: 0.8662
Epoch 104/200
 - 0s - loss: 0.3850 - accuracy: 0.8383 - val_loss: 0.3360 - val_accuracy: 0.8687
Epoch 105/200
 - 0s - loss: 0.3800 - accuracy: 0.8403 - val_loss: 0.3364 - val_accuracy: 0.8662
Epoch 106/200
 - 0s - loss: 0.3801 - accuracy: 0.8456 - val_loss: 0.3383 - val_accuracy: 0.8625
Epoch 107/200
 - 0s - loss: 0.3815 - accuracy: 0.8419 - val_loss: 0.3379 - val_accuracy: 0.8625
Epoch 108/200
 - 0s - loss: 0.3825 - accuracy: 0.8421 - val_loss: 0.3377 - val_accuracy: 0.8625
Epoch 109/200
 - 0s - loss: 0.3787 - accuracy: 0.8436 - val_loss: 0.3341 - val_accuracy: 0.8675
Epoch 110/200
 - 0s - loss: 0.3815 - accuracy: 0.8397 - val_loss: 0.3374 - val_accuracy: 0.8662
Epoch 111/200
 - 0s - loss: 0.3781 - accuracy: 0.8440 - val_loss: 0.3379 - val_accuracy: 0.8612
Epoch 112/200
 - 0s - loss: 0.3790 - accuracy: 0.8410 - val_loss: 0.3365 - val_accuracy: 0.8662
Epoch 113/200
 - 0s - loss: 0.3852 - accuracy: 0.8432 - val_loss: 0.3371 - val_accuracy: 0.8600
Epoch 114/200
 - 0s - loss: 0.3736 - accuracy: 0.8464 - val_loss: 0.3347 - val_accuracy: 0.8625
Epoch 115/200
 - 0s - loss: 0.3773 - accuracy: 0.8443 - val_loss: 0.3360 - val_accuracy: 0.8637
Epoch 116/200
 - 0s - loss: 0.3735 - accuracy: 0.8440 - val_loss: 0.3330 - val_accuracy: 0.8700
Epoch 117/200
 - 0s - loss: 0.3771 - accuracy: 0.8458 - val_loss: 0.3354 - val_accuracy: 0.8675
Epoch 118/200
 - 0s - loss: 0.3765 - accuracy: 0.8431 - val_loss: 0.3370 - val_accuracy: 0.8662
Epoch 119/200
 - 0s - loss: 0.3752 - accuracy: 0.8438 - val_loss: 0.3375 - val_accuracy: 0.8625
Epoch 120/200
 - 0s - loss: 0.3671 - accuracy: 0.8503 - val_loss: 0.3339 - val_accuracy: 0.8687
Epoch 121/200
 - 0s - loss: 0.3792 - accuracy: 0.8421 - val_loss: 0.3345 - val_accuracy: 0.8675
Epoch 122/200
 - 0s - loss: 0.3752 - accuracy: 0.8442 - val_loss: 0.3340 - val_accuracy: 0.8675
Epoch 123/200
 - 0s - loss: 0.3718 - accuracy: 0.8468 - val_loss: 0.3324 - val_accuracy: 0.8662
Epoch 124/200
 - 0s - loss: 0.3807 - accuracy: 0.8369 - val_loss: 0.3368 - val_accuracy: 0.8587
Epoch 125/200
 - 0s - loss: 0.3761 - accuracy: 0.8439 - val_loss: 0.3387 - val_accuracy: 0.8575
Epoch 126/200
 - 0s - loss: 0.3790 - accuracy: 0.8443 - val_loss: 0.3335 - val_accuracy: 0.8575
Epoch 127/200
 - 0s - loss: 0.3743 - accuracy: 0.8447 - val_loss: 0.3337 - val_accuracy: 0.8675
Epoch 128/200
 - 0s - loss: 0.3770 - accuracy: 0.8438 - val_loss: 0.3315 - val_accuracy: 0.8675
Epoch 129/200
 - 0s - loss: 0.3702 - accuracy: 0.8469 - val_loss: 0.3321 - val_accuracy: 0.8650
Epoch 130/200
 - 0s - loss: 0.3697 - accuracy: 0.8476 - val_loss: 0.3338 - val_accuracy: 0.8662
Epoch 131/200
 - 0s - loss: 0.3712 - accuracy: 0.8457 - val_loss: 0.3324 - val_accuracy: 0.8650
Epoch 132/200
 - 0s - loss: 0.3732 - accuracy: 0.8439 - val_loss: 0.3330 - val_accuracy: 0.8700
Epoch 133/200
 - 0s - loss: 0.3758 - accuracy: 0.8447 - val_loss: 0.3325 - val_accuracy: 0.8612
Epoch 134/200
 - 0s - loss: 0.3732 - accuracy: 0.8489 - val_loss: 0.3332 - val_accuracy: 0.8675
Epoch 135/200
 - 0s - loss: 0.3717 - accuracy: 0.8439 - val_loss: 0.3348 - val_accuracy: 0.8650
Epoch 136/200
 - 0s - loss: 0.3763 - accuracy: 0.8418 - val_loss: 0.3345 - val_accuracy: 0.8650
Epoch 137/200
 - 0s - loss: 0.3748 - accuracy: 0.8447 - val_loss: 0.3300 - val_accuracy: 0.8625
Epoch 138/200
 - 0s - loss: 0.3706 - accuracy: 0.8435 - val_loss: 0.3298 - val_accuracy: 0.8662
Epoch 139/200
 - 0s - loss: 0.3759 - accuracy: 0.8439 - val_loss: 0.3344 - val_accuracy: 0.8612
Epoch 140/200
 - 0s - loss: 0.3712 - accuracy: 0.8462 - val_loss: 0.3319 - val_accuracy: 0.8662
Epoch 141/200
 - 0s - loss: 0.3694 - accuracy: 0.8460 - val_loss: 0.3326 - val_accuracy: 0.8700
Epoch 142/200
 - 0s - loss: 0.3697 - accuracy: 0.8457 - val_loss: 0.3313 - val_accuracy: 0.8687
Epoch 143/200
 - 0s - loss: 0.3675 - accuracy: 0.8481 - val_loss: 0.3346 - val_accuracy: 0.8662
Epoch 144/200
 - 0s - loss: 0.3710 - accuracy: 0.8443 - val_loss: 0.3313 - val_accuracy: 0.8650
Epoch 145/200
 - 0s - loss: 0.3684 - accuracy: 0.8444 - val_loss: 0.3292 - val_accuracy: 0.8637
Epoch 146/200
 - 0s - loss: 0.3730 - accuracy: 0.8453 - val_loss: 0.3283 - val_accuracy: 0.8637
Epoch 147/200
 - 0s - loss: 0.3715 - accuracy: 0.8449 - val_loss: 0.3297 - val_accuracy: 0.8637
Epoch 148/200
 - 0s - loss: 0.3792 - accuracy: 0.8410 - val_loss: 0.3337 - val_accuracy: 0.8625
Epoch 149/200
 - 0s - loss: 0.3686 - accuracy: 0.8479 - val_loss: 0.3296 - val_accuracy: 0.8675
Epoch 150/200
 - 0s - loss: 0.3705 - accuracy: 0.8451 - val_loss: 0.3309 - val_accuracy: 0.8650
Epoch 151/200
 - 0s - loss: 0.3725 - accuracy: 0.8468 - val_loss: 0.3293 - val_accuracy: 0.8687
Epoch 152/200
 - 0s - loss: 0.3710 - accuracy: 0.8451 - val_loss: 0.3318 - val_accuracy: 0.8612
Epoch 153/200
 - 0s - loss: 0.3736 - accuracy: 0.8440 - val_loss: 0.3285 - val_accuracy: 0.8687
Epoch 154/200
 - 0s - loss: 0.3715 - accuracy: 0.8451 - val_loss: 0.3278 - val_accuracy: 0.8712
Epoch 155/200
 - 0s - loss: 0.3698 - accuracy: 0.8454 - val_loss: 0.3276 - val_accuracy: 0.8700
Epoch 156/200
 - 0s - loss: 0.3672 - accuracy: 0.8486 - val_loss: 0.3299 - val_accuracy: 0.8662
Epoch 157/200
 - 0s - loss: 0.3730 - accuracy: 0.8436 - val_loss: 0.3266 - val_accuracy: 0.8700
Epoch 158/200
 - 0s - loss: 0.3739 - accuracy: 0.8446 - val_loss: 0.3295 - val_accuracy: 0.8662
Epoch 159/200
 - 0s - loss: 0.3687 - accuracy: 0.8468 - val_loss: 0.3308 - val_accuracy: 0.8650
Epoch 160/200
 - 0s - loss: 0.3700 - accuracy: 0.8467 - val_loss: 0.3283 - val_accuracy: 0.8675
Epoch 161/200
 - 0s - loss: 0.3726 - accuracy: 0.8456 - val_loss: 0.3322 - val_accuracy: 0.8662
Epoch 162/200
 - 0s - loss: 0.3717 - accuracy: 0.8435 - val_loss: 0.3322 - val_accuracy: 0.8650
Epoch 163/200
 - 0s - loss: 0.3720 - accuracy: 0.8432 - val_loss: 0.3328 - val_accuracy: 0.8687
Epoch 164/200
 - 0s - loss: 0.3698 - accuracy: 0.8475 - val_loss: 0.3329 - val_accuracy: 0.8662
Epoch 165/200
 - 0s - loss: 0.3673 - accuracy: 0.8474 - val_loss: 0.3317 - val_accuracy: 0.8687
Epoch 166/200
 - 0s - loss: 0.3739 - accuracy: 0.8453 - val_loss: 0.3317 - val_accuracy: 0.8662
Epoch 167/200
 - 0s - loss: 0.3708 - accuracy: 0.8453 - val_loss: 0.3302 - val_accuracy: 0.8637
Epoch 168/200
 - 0s - loss: 0.3724 - accuracy: 0.8451 - val_loss: 0.3337 - val_accuracy: 0.8637
Epoch 169/200
 - 0s - loss: 0.3683 - accuracy: 0.8487 - val_loss: 0.3318 - val_accuracy: 0.8662
Epoch 170/200
 - 0s - loss: 0.3694 - accuracy: 0.8485 - val_loss: 0.3354 - val_accuracy: 0.8637
Epoch 171/200
 - 0s - loss: 0.3665 - accuracy: 0.8468 - val_loss: 0.3304 - val_accuracy: 0.8675
Epoch 172/200
 - 0s - loss: 0.3681 - accuracy: 0.8464 - val_loss: 0.3281 - val_accuracy: 0.8675

Epoch 173/200
 - 0s - loss: 0.3679 - accuracy: 0.8458 - val_loss: 0.3304 - val_accuracy: 0.8687
Epoch 174/200
 - 0s - loss: 0.3700 - accuracy: 0.8440 - val_loss: 0.3328 - val_accuracy: 0.8662
Epoch 175/200
 - 0s - loss: 0.3721 - accuracy: 0.8440 - val_loss: 0.3333 - val_accuracy: 0.8687
Epoch 176/200
 - 0s - loss: 0.3724 - accuracy: 0.8435 - val_loss: 0.3319 - val_accuracy: 0.8675
Epoch 177/200
 - 0s - loss: 0.3681 - accuracy: 0.8490 - val_loss: 0.3277 - val_accuracy: 0.8662
Epoch 178/200
 - 0s - loss: 0.3683 - accuracy: 0.8467 - val_loss: 0.3317 - val_accuracy: 0.8637
Epoch 179/200
 - 0s - loss: 0.3674 - accuracy: 0.8458 - val_loss: 0.3309 - val_accuracy: 0.8637
Epoch 180/200
 - 0s - loss: 0.3677 - accuracy: 0.8489 - val_loss: 0.3282 - val_accuracy: 0.8712
Epoch 181/200
 - 0s - loss: 0.3674 - accuracy: 0.8464 - val_loss: 0.3301 - val_accuracy: 0.8637
Epoch 182/200
 - 0s - loss: 0.3703 - accuracy: 0.8474 - val_loss: 0.3285 - val_accuracy: 0.8650
Epoch 183/200
 - 0s - loss: 0.3634 - accuracy: 0.8494 - val_loss: 0.3286 - val_accuracy: 0.8650
Epoch 184/200
 - 0s - loss: 0.3732 - accuracy: 0.8460 - val_loss: 0.3309 - val_accuracy: 0.8675
Epoch 185/200
 - 0s - loss: 0.3674 - accuracy: 0.8486 - val_loss: 0.3328 - val_accuracy: 0.8600
Epoch 186/200
 - 0s - loss: 0.3738 - accuracy: 0.8429 - val_loss: 0.3306 - val_accuracy: 0.8675
Epoch 187/200
 - 0s - loss: 0.3690 - accuracy: 0.8478 - val_loss: 0.3311 - val_accuracy: 0.8612
Epoch 188/200
 - 0s - loss: 0.3716 - accuracy: 0.8422 - val_loss: 0.3304 - val_accuracy: 0.8650
Epoch 189/200
 - 0s - loss: 0.3675 - accuracy: 0.8444 - val_loss: 0.3313 - val_accuracy: 0.8625
Epoch 190/200
 - 0s - loss: 0.3670 - accuracy: 0.8515 - val_loss: 0.3323 - val_accuracy: 0.8637
Epoch 191/200
 - 0s - loss: 0.3707 - accuracy: 0.8474 - val_loss: 0.3297 - val_accuracy: 0.8675
Epoch 192/200
 - 0s - loss: 0.3699 - accuracy: 0.8454 - val_loss: 0.3294 - val_accuracy: 0.8637
Epoch 193/200
 - 0s - loss: 0.3691 - accuracy: 0.8479 - val_loss: 0.3305 - val_accuracy: 0.8650
Epoch 194/200
 - 0s - loss: 0.3674 - accuracy: 0.8457 - val_loss: 0.3283 - val_accuracy: 0.8637
Epoch 195/200
 - 0s - loss: 0.3735 - accuracy: 0.8476 - val_loss: 0.3301 - val_accuracy: 0.8650
Epoch 196/200
 - 0s - loss: 0.3683 - accuracy: 0.8486 - val_loss: 0.3321 - val_accuracy: 0.8612
Epoch 197/200
 - 0s - loss: 0.3652 - accuracy: 0.8496 - val_loss: 0.3323 - val_accuracy: 0.8612
Epoch 198/200
 - 0s - loss: 0.3744 - accuracy: 0.8467 - val_loss: 0.3308 - val_accuracy: 0.8637
Epoch 199/200
 - 0s - loss: 0.3738 - accuracy: 0.8451 - val_loss: 0.3288 - val_accuracy: 0.8625
Epoch 200/200
 - 0s - loss: 0.3762 - accuracy: 0.8426 - val_loss: 0.3345 - val_accuracy: 0.8612

In [41]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

[[0.27662158]
 [0.3280355 ]
 [0.26075011]
 [0.11784413]
 [0.11433327]]

In [42]:
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]

In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1556   39]
 [ 236  169]]

In [44]:
#Accuracy of our NN
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.25 % of data was classified correctly